### ISSUE TITLE
Unable to extract photos

### ISSUE THREAD

**Issue by WingedDrifter** [kwsch/NewSnap#2]
I'm unsure if I'm using the program correctly. I can't get it to extract photos.

I extract the .zip. I put my save folder into the same folder as the program, then dragged the save folder on top of the .exe, and cmd window pops up for a brief moment before closing. I saw text once, but it closes too quickly to get a screenshot of what it says.

I installed both the x64 + x86 versions of the .net framework. Running Win10.
I dumped my save using JKSV. This is what the folder looks like.
![2021-05-01-15 50-Crow-002887](https://user-images.githubusercontent.com/75647829/116823817-f49cb000-ab43-11eb-94a9-27a399839da7.png)

Help? I really want to get my photos extracted!

**Comment by sora10pls** [comment]
Works fine for me on the hotfixed build under releases.
Run the following from command prompt under the folder where `NewSnap.App.exe` is located:

```
NewSnap.App.exe -sav <path_to_save_here>
```
You'll then be greeted to a bunch of new folders, `XX`, which will contain your extracted save data contents.
![image](https://user-images.githubusercontent.com/17801814/116826281-3a1ba600-ab61-11eb-9ae4-1535faab5a52.png)

**Comment by WingedDrifter** [comment]
Ah, thank you! I finally got it to work!
