### ISSUE TITLE
Decrypt/encrypt only?

### ISSUE THREAD

**Issue by Grogrogro** [kwsch/NewSnap#3]
Hey!
Could you please add --dec/--enc command to the tool to decrypt/re-encrypt drps only?

Older drp tool (https://github.com/Sammi-Husky/Pokken-Tools) has this functionality.

Thank you!

**Comment by kwsch** [comment]
What's the use case for only decrypt/encrypt?

Individual file entries are CRC'd before compression, so hex editing won't really be possible.

The program already supports dumping all entries, and modifying too.

**Comment by Grogrogro** [comment]
Oh, well. Just wanted to recompress files, for a smaller home backup. I know it's a niche request. But probably if not very hard - could be implemented.

Also I think that currently re-importing is not working.

What steps did I do.

1) Dumped all files from a small test drp:
NewSnap.App.exe -drp CH_001.drp CH_001

2) Filled with zeroes all files in a dumped folder to make them new, just for test.

3) Reimported the folder to a copy of CH_001.drp
NewSnap.App.exe -mf CH_001_new.drp CH_001_zeroed
No error messages, just Done! as a result.

4) Dumped all files from this "reimported" drp
NewSnap.App.exe -drp CH_001_new.drp CH_001_new

Compared all extracted files in both folders: All files in CH_001_new were exact as in original CH_001, not filled with zeroes.

Am I doing something wrong?

**Comment by Grogrogro** [comment]
Oh, my bad. The folder contained subfolder, not only files. After I moved files properly, it worked as intended. But it's strange that the result drp file was the same size, proably zerofied files should be compressed much better.

Also, when I reimported original files to the pack with zeroed ones - the size of the final drp doubled.

**Comment by kwsch** [comment]
Unable to replicate with a test method https://github.com/kwsch/NewSnap/commit/44656002c0e31480d739897b5f1a2fb4eda4cd64 which:
- Loads an unmodified DRPF
- Sets all file data to zeroed arrays of same length
- Saves the modified DRPF; confirms the size shrinks drastically
- Loads the modified DRPF
- Sets all file data to the original file data
- Saves the newly modified DRPF
- Final result matches the original DRPF's data content exactly.

Double check your command line arguments for where you're saving the output drp file; the logic is working fine.

**Comment by Grogrogro** [comment]
I've made a zip with my commands, small drp and your latest available build. The problem persists.
The drp, filled with nullified files doesn't change in size and if you fc /b it with original - just a few bytes actually change.

[test.zip](https://github.com/kwsch/NewSnap/files/6416524/test.zip)

Maybe internal test function didn't properly propagate to the actual rebuilding command?

**Comment by kwsch** [comment]
Fixed; the saving of the drpf resulted in it appending new data to the old drpf, rather than wiping the file first.

The `_new` file you provided is an invalid-appended file, so I just copied the original and all worked fine.
![image](https://user-images.githubusercontent.com/6393368/116913178-00e54380-abfe-11eb-841b-6f0a48b54caf.png)

**Comment by Grogrogro** [comment]
Yes, new build works as intended, thank you! On the other note - is the static build of the tool available?

**Comment by kwsch** [comment]
I posted a new release (0.3) which is current with the above referenced commit. That should be it?

**Comment by Grogrogro** [comment]
I mean the build w/o any dependencies. If it's possible at all, I don't know how that NET stuff works :)

**Comment by kwsch** [comment]
Similar to other projects that may use the ".NET Framework 4.x" runtime, this project uses a more recent runtime (.NET Core 3.1), which is linked in the readme: https://dotnet.microsoft.com/download/dotnet/3.1

You'd want to install the `.NET Runtime 3.1.14` to run the console application that is posted in the releases section. There aren't any external dependencies in this project, so the files in the release zip is all you'd need.

I think there is a way to have it build with the necessary files from the runtime as a single-folder install (similar to Ryujinx), but that'd be platform specific (win64/linux/mac) and ~30MB when zipped, as opposed to the 120KB for the current release (which depends on the runtime being installed).

**Comment by kwsch** [comment]
```html
    <PublishSingleFile>true</PublishSingleFile>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishTrimmed>true</PublishTrimmed>
    <PublishReadyToRun>true</PublishReadyToRun>
  ```

Adding the above 4 lines to the NewSnap.App.csproj & rebuilding all will cause it to build a platform specific install, as referenced above.

**Comment by Grogrogro** [comment]
Thanks, I tried to build it with Rider, but faced so many errors on build, though NET component was installed... Could you please upload that Windows independent build separately, if you don't want to post it as part of releases page?

Many thanks for fast replies and fixes!

**Comment by kwsch** [comment]
> Could you please upload that Windows independent build separately, if you don't want to post it as part of releases page?

Added it to the latest release (30MB zip), should work.

**Comment by Grogrogro** [comment]
Many thanks!
