### ISSUE TITLE
[Help] File formats information

### ISSUE THREAD

**Issue by MagicMimi** [kwsch/NewSnap#5]
Hello !
First of all, thanks a ton for the hard work you and Scires put into this tool, it's working perfectly !
I'm sorry if this is a bit out of topic but I'm desperate about this : do you know any way to visualize/repack the animation files ? I saw that the format was used in Smash but apparently it had some changes so existing tools don't work :(
I was wondering if you knew any tool to deal with these, the only thing I managed to find was this tweet here but the poster didn't answer to my DM request, do you know them by any chance ? Or someone else that worked on it ? https://twitter.com/joschimy/status/1400383441175298048
Once again thanks a lot for all the great work, I hope you have a great week !
Take care !

**Comment by kwsch** [comment]
Nope, nothing here in this project deals with the animation files. Not really within the scope of this program.
